In [14]:
import sys
!{sys.executable} -m pip install -qq pandas numpy matplotlib seaborn scikit-learn
# add more here as needed

***RallyRF***  
*Cam Bitter, Sebastian Pantzer, Danny Smith*  
  
Accessible via [this](https://github.com/CamBitter/RallyRF) github repository

**Abstract**

For decades, the sport of Tennis has been meticulously analyzed. Its design naturally lends itself to the development of advanced metrics that serve to reduce complicated gameplay to an interaction of statistics. In this project we aim to take advantage of these metrics to successfully predict outcomes of professional tennis matches. We used an existing database, consisting of the majority of professional tennis matches played since the 1960’s. After cleaning the data, we engineered multiple feature sets of summary statistics based on previous match stats. We trained and tested a Random Forest model on each feature set and compared the results to other models, including another ensemble model--a Gradient-Boosted Decision Tree. In the end, we reached a match prediction accuracy of 63%, while other models reached slightly lower accuracy marks. While our results demonstrate a successful implementation of less complex machine learning algorithms, we are cognizant of potential performance ceilings due to data limitations.

**Introduction:**  
The main motivation behind this project is to learn an more advanced ML technique (that still holds up in modern times) in great detail by building it from the ground up. Random forests are widely popular and effective at medium sized tabular data, and are much more efficient than deep learning models.  

Tennis is a very hard sport to predict, with variables like mental state having huge implications on match outcome. By applying our custom random forest to a real-world prediction problem, we hope to learn about what affects the performance of the model we built and compare our model to research findings.  

The primary source we used was *Random forest model identifies serve strength as a key
predictor of tennis match outcome*, by Zijian Gao and Amanda Kowalczyk. They used the Jeff Sackmann tennis dataset (which we also used, more on that later) and random forests to predict winning outcomes of tennis matches. We followed many of the same procedures and data pipelines as them, in hopes to also gain an accuracy score in the 80% range.  
We also examined the work done in *Tennis Match Prediction using Machine Leanring*, a thesis paper by Ajay Krishna Amudan. Amudan did similar work to Gao and Kowalczyk, but did different work with the data features. We tried integrating elements from both projects in our random forest implementation.
  
Amudan, A. (2019). *Tennis Match Prediction using Machine Leanring*. Stanford University, CS229: Machine Learning. [https://cs229.stanford.edu/proj2019aut/data/assignment_308832_raw/26647696.pdf](https://cs229.stanford.edu/proj2019aut/data/assignment_308832_raw/26647696.pdf)  
  
Gao, Z., & Kowalczyk, A. (2021). Random forest model identifies serve strength as a key predictor of tennis match outcome. *Journal of Sports Analytics*, 7(4), 255–262. [https://doi.org/10.3233/jsa-200515](https://doi.org/10.3233/jsa-200515)

**Values:**  
*Users:*  
This project can and may be used by a range of people, and affect even more. The chief users are likely players/coaches, and gamblers/people who engage in sports betting. Since this project uses information from a large number of tennis players, it is possible to affect those players without their knowledge.  
*Beneficiaries:*  
It is likely the most effective use of this program is in sports betting, so those who benefit most may be people trying to beat conventional odds. However, individual players looking to learn what features and characteristics of play matter most will also be positively affected.  
*Victims:*  
Those negatively affected by this project are parallels of the beneficiaries. - gamblers and players. A powerful prediction tool can both hurt sports bettors without the tool, and give a false sense of security to those who do possess it.  
Additionally, accurate models can harm professional players, who could receive more scrutiny and pressure to perform.  
It is important to note these effects, both positive and negative, are relatively lofty. It is unlikely this specific tool will become popularized enough to have impacts at the scale discussed here.  
*Personal Stake:*  
As a group, we have a few layers of personal connection to this project. Cam is an experienced tennis player, and follows the sport professionally as well as leads the club team at Middlebury. Sebastian, while less involved in tennis, is a member of the track team. Danny plays for the Club Quadball team, and dabbles in other sports, including tennis. Overall, every member of the group has some level of person interest and stake in statistics of athletics. Beyond the sport itself, we all have some academic background in statistics, and were interesting in developing these connections when implementing a Random Forest as a new ML technique.  
*Is the world better off for this project?*  
Realistically, not really. This project has arguably brought engagement in learning to at least the three of us, so in that sense it has had a positive impact. However, the effect may not go beyond that.

**Data**  
Our dataset is [JeffSackmann ATP Data Repository](https://github.com/jeffsackmann/tennis_atp). It contains ATP tennis match results spanning back to 1964, with over 40,000 matches. It is freely available for non-commercial use under a [creative commons license](https://creativecommons.org/licenses/by-nc-sa/4.0/).  
The original dataset has these features:  
```text
tourney_id, tourney_name, surface, draw_size, tourney_level, tourney_date, match_num, 
winner_id, winner_seed, winner_entry, winner_name, winner_hand, winner_ht, winner_ioc, 
winner_age, loser_id, loser_seed, loser_entry, loser_name, loser_hand, loser_ht, 
loser_ioc, loser_age, score, best_of, round, minutes, w_ace, w_df, w_svpt, w_1stIn, 
w_1stWon, w_2ndWon, w_SvGms, w_bpSaved, w_bpFaced, l_ace, l_df, l_svpt, l_1stIn, 
l_1stWon, l_2ndWon, l_SvGms, l_bpSaved, l_bpFaced, winner_rank, winner_rank_points, 
loser_rank, loser_rank_points
```   

Sackmann's data goes all the way back to the 1980s. However, since many of the older matches are incomplete from a statistic tracking perspective, and the style of play in tennis has shifted greatly in the past 30 years, we chose to only look at data from the year 2000 onward. Also, Sackmann keeps track of both doubles and singles matches. We are only using data from singles. Many of these features are *post match* statistics, so we must do some level of data analysis to get stats for a player prior to the match they are competing in. Additionally, per Gao et al., we want to work with difference in player stats. Instead of storing *winner_ht* and *loser_ht*, we can get the same information with *ht_diff*. However, as mentioned before, we also wanted to experiment with not comparing some features. The thought is, the difference between a seed 1 and seed 10 player could be much larger than that between a seed 201 and 210 player. So, we created three distinct data files:

In [6]:
import pandas as pd

df_all_diffs = pd.read_csv('data/cleaned/all_diffs.csv')
df_some_diffs = pd.read_csv('data/cleaned/some_diffs.csv')
df_no_diffs = pd.read_csv('data/cleaned/no_diffs.csv')

,tourney_id,tourney_date,surface,round,p1_name,p2_name,p1_won,surface_hard,surface_clay,surface_grass,...,height_diff,surface_win_pct_diff,ace_vs_df_diff,first_in_diff,first_won_diff,second_won_diff,bp_saved_pct_diff,bp_converted_pct_diff,win_pct_diff,games_played_diff
0,2000-338,20000110,Hard,R32,Adrian Voinea,Vincent Spadea,1,1,0,0,...,2.0,0.000000,1.400000,0.060928,0.153509,0.209459,0.514286,-1.000000,0.000000,0.0
1,2000-338,20000110,Hard,R32,Daniel Vacek,Jean Rene Lisnard,1,1,0,0,...,17.0,0.000000,0.400000,0.020263,-0.004918,-0.306265,-0.324405,0.114286,0.000000,0.0
2,2000-338,20000110,Hard,R32,Lleyton Hewitt,Sebastien Grosjean,1,1,0,0,...,5.0,0.333333,-1.444444,0.001931,-0.022631,0.078335,-0.041667,-0.200000,0.333333,2.0
3,2000-338,20000110,Hard,R32,Slava Dosedel,Mark Woodforde,1,1,0,0,...,-5.0,0.500000,-0.333333,0.091800,0.040213,0.178623,-0.051136,0.000000,0.500000,1.0
4,2000-301,20000110,Hard,R32,Sjeng Schalken,Goran Ivanisevic,1,1,0,0,...,0.0,0.666667,-0.781818,0.021985,0.025253,-0.056746,-0.214286,-0.687500,0.666667,2.0

```df_no_diffs```
 contains most of the same features in the original dataset. Note that some features, like the surface type, has been one-hot-encoded:

In [11]:
df_no_diffs.head()

,tourney_id,tourney_date,round,p1_name,p2_name,p1_won,surface_hard,surface_clay,surface_grass,p1_rank,...,p1_second_won,p2_second_won,p1_bp_saved_pct,p2_bp_saved_pct,p1_bp_converted_pct,p2_bp_converted_pct,p1_win_pct,p2_win_pct,p1_games_played,p2_games_played
0,2000-338,20000110,R32,Adrian Voinea,Vincent Spadea,1,1,0,0,102.0,...,0.459459,0.250000,0.800000,0.285714,0.0000,1.000000,0.000000,0.000000,1.0,1.0
1,2000-338,20000110,R32,Daniel Vacek,Jean Rene Lisnard,1,1,0,0,41.0,...,0.260000,0.566265,0.437500,0.761905,0.4000,0.285714,0.500000,0.500000,2.0,2.0
2,2000-338,20000110,R32,Lleyton Hewitt,Sebastien Grosjean,1,1,0,0,21.0,...,0.604651,0.526316,0.708333,0.750000,0.5500,0.750000,1.000000,0.666667,5.0,3.0
3,2000-338,20000110,R32,Slava Dosedel,Mark Woodforde,1,1,0,0,69.0,...,0.560976,0.382353,0.636364,0.687500,0.3750,0.375000,0.500000,0.000000,2.0,1.0
4,2000-301,20000110,R32,Sjeng Schalken,Goran Ivanisevic,1,1,0,0,37.0,...,0.486111,0.542857,0.500000,0.714286,0.3125,1.000000,0.666667,0.000000,3.0,1.0

```df_some_diffs``` has some augmentation. Player seed is still individually tracked:

In [12]:
df_some_diffs.head()

,tourney_id,tourney_date,round,p1_name,p2_name,p1_won,surface_hard,surface_clay,surface_grass,p1_rank,...,age_diff,surface_win_pct_diff,ace_vs_df_diff,first_in_diff,first_won_diff,second_won_diff,bp_saved_pct_diff,bp_converted_pct_diff,win_pct_diff,games_played_diff
0,2000-338,20000110,R32,Adrian Voinea,Vincent Spadea,1,1,0,0,102.0,...,0.0,0.000000,1.400000,0.060928,0.153509,0.209459,0.514286,-1.000000,0.000000,0.0
1,2000-338,20000110,R32,Daniel Vacek,Jean Rene Lisnard,1,1,0,0,41.0,...,8.5,0.000000,0.400000,0.020263,-0.004918,-0.306265,-0.324405,0.114286,0.000000,0.0
2,2000-338,20000110,R32,Lleyton Hewitt,Sebastien Grosjean,1,1,0,0,21.0,...,-2.8,0.333333,-1.444444,0.001931,-0.022631,0.078335,-0.041667,-0.200000,0.333333,2.0
3,2000-338,20000110,R32,Slava Dosedel,Mark Woodforde,1,1,0,0,69.0,...,-4.8,0.500000,-0.333333,0.091800,0.040213,0.178623,-0.051136,0.000000,0.500000,1.0
4,2000-301,20000110,R32,Sjeng Schalken,Goran Ivanisevic,1,1,0,0,37.0,...,-5.0,0.666667,-0.781818,0.021985,0.025253,-0.056746,-0.214286,-0.687500,0.666667,2.0

```df_all_diffs``` joins all features possible. To account for overfitting, and to add more data, we randomly flip rows, switching p1 and p2, and inverting each difference:

In [13]:
df_all_diffs.head()

,tourney_id,tourney_date,surface,round,p1_name,p2_name,p1_won,surface_hard,surface_clay,surface_grass,...,height_diff,surface_win_pct_diff,ace_vs_df_diff,first_in_diff,first_won_diff,second_won_diff,bp_saved_pct_diff,bp_converted_pct_diff,win_pct_diff,games_played_diff
0,2000-338,20000110,Hard,R32,Adrian Voinea,Vincent Spadea,1,1,0,0,...,2.0,0.000000,1.400000,0.060928,0.153509,0.209459,0.514286,-1.000000,0.000000,0.0
1,2000-338,20000110,Hard,R32,Daniel Vacek,Jean Rene Lisnard,1,1,0,0,...,17.0,0.000000,0.400000,0.020263,-0.004918,-0.306265,-0.324405,0.114286,0.000000,0.0
2,2000-338,20000110,Hard,R32,Lleyton Hewitt,Sebastien Grosjean,1,1,0,0,...,5.0,0.333333,-1.444444,0.001931,-0.022631,0.078335,-0.041667,-0.200000,0.333333,2.0
3,2000-338,20000110,Hard,R32,Slava Dosedel,Mark Woodforde,1,1,0,0,...,-5.0,0.500000,-0.333333,0.091800,0.040213,0.178623,-0.051136,0.000000,0.500000,1.0
4,2000-301,20000110,Hard,R32,Sjeng Schalken,Goran Ivanisevic,1,1,0,0,...,0.0,0.666667,-0.781818,0.021985,0.025253,-0.056746,-0.214286,-0.687500,0.666667,2.0

**Our Approach**
*features used*  
*data augmentation*  
*models*  
*training*  
*evaluation*  

// runnable demo

**Results**

// include graphs AND explanation

**Conclusion**  
*What Worked*  
*Did we meet our goals*  
*Results compared to similar problems*  
*Future work*

**Group Contributions**  
// who worked on which parts of the source code  
// who performed or visualized experiments  
// who led writing of each blog post section  
// "etc"